apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: back
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
           claimName: pvc-guestbook
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: task-pv-storage  
